// lib/bi-compras.js — Solicitação de compra com aprovação Z-API (F2)
//
// State machine:
//   rascunho → aguardando_aprovacao → (aprovada | reprovada | ajuste)
//   aprovada → pedido_enviado → recebida
//   reprovada/ajuste podem voltar pra aguardando_aprovacao via reenvio
//
// Quem aprova: Morgana (cadastrada em bi_aprovadores com escopo 'compras' ou geral).
// Notificação: bi-zapi-compras dispara WhatsApp.
// Match com NF-e: quando NF chega, se emitente_cnpj === fornecedor_id da
// solicitação e valor próximo, sugerimos match.

const db = require('./bi-estoque-db');
const biEstoque = require('./bi-estoque');

function _pool() { return db.getPool(); }
const uid = (p='comp_') => p + Math.random().toString(36).slice(2,9) + Date.now().toString(36).slice(-3);

const STATUS = {
  RASCUNHO: 'rascunho',
  AGUARDANDO: 'aguardando_aprovacao',
  APROVADA: 'aprovada',
  REPROVADA: 'reprovada',
  AJUSTE: 'ajuste',
  PEDIDO_ENVIADO: 'pedido_enviado',
  RECEBIDA: 'recebida',
  CANCELADA: 'cancelada',
};

const URGENCIAS = ['baixa', 'normal', 'alta', 'urgente'];

async function ensureTable() {
  const pool = _pool();
  if (!pool) return;
  const sqls = [
    `CREATE TABLE IF NOT EXISTS bi_compra_solicitacao (
      id TEXT PRIMARY KEY,
      numero_seq INT GENERATED BY DEFAULT AS IDENTITY,
      empresa_id TEXT REFERENCES bi_empresas(id) ON DELETE SET NULL,
      empresa_bi TEXT,                      -- empresa BI (localStorage) — pra contas a pagar
      fornecedor_id TEXT REFERENCES bi_fornecedores(id) ON DELETE SET NULL,
      fornecedor_nome TEXT,                 -- snapshot pra exibir
      urgencia TEXT NOT NULL DEFAULT 'normal',
      justificativa TEXT,
      observacoes TEXT,
      valor_estimado_total NUMERIC(14,2) DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'rascunho',
      token_aprovacao TEXT,                 -- gerado ao submeter, validado no Z-API
      token_expira_em TIMESTAMPTZ,
      solicitante_username TEXT,
      submetida_em TIMESTAMPTZ,
      aprovador_username TEXT,
      aprovador_telefone TEXT,
      decidida_em TIMESTAMPTZ,
      motivo TEXT,                          -- motivo reprovação ou observação de ajuste
      pedido_enviado_em TIMESTAMPTZ,
      pedido_enviado_por TEXT,
      pdf_gerado_em TIMESTAMPTZ,
      nf_id TEXT REFERENCES bi_nf_entrada(id) ON DELETE SET NULL,
      recebida_em TIMESTAMPTZ,
      historico JSONB DEFAULT '[]'::jsonb,  -- array de eventos {ts, tipo, who, payload}
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ
    )`,
    `CREATE INDEX IF NOT EXISTS idx_comp_status ON bi_compra_solicitacao (status)`,
    `CREATE INDEX IF NOT EXISTS idx_comp_token ON bi_compra_solicitacao (token_aprovacao) WHERE token_aprovacao IS NOT NULL`,
    `CREATE INDEX IF NOT EXISTS idx_comp_fornec ON bi_compra_solicitacao (fornecedor_id)`,
    `CREATE INDEX IF NOT EXISTS idx_comp_numero ON bi_compra_solicitacao (numero_seq)`,

    `CREATE TABLE IF NOT EXISTS bi_compra_item (
      id TEXT PRIMARY KEY,
      solicitacao_id TEXT NOT NULL REFERENCES bi_compra_solicitacao(id) ON DELETE CASCADE,
      ordem INT NOT NULL,
      produto_id TEXT REFERENCES bi_produtos(id) ON DELETE SET NULL,
      produto_nome TEXT,                    -- snapshot
      sku TEXT,
      qtd NUMERIC(14,4) NOT NULL,
      custo_unit_estimado NUMERIC(14,4) DEFAULT 0,
      valor_estimado NUMERIC(14,2) DEFAULT 0,
      observacoes TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS idx_compi_sol ON bi_compra_item (solicitacao_id)`,
  ];
  for (const sql of sqls) {
    try { await pool.query(sql); }
    catch(e) { console.error('[bi-compras ensure]', e.message); throw e; }
  }
  console.log('[bi-compras] tabelas criadas/verificadas');
}

function _newToken() { return 'COMP-' + Math.random().toString(36).slice(2,7).toUpperCase(); }
function _expiraEm(diasUteis=7) {
  const d = new Date(); d.setDate(d.getDate() + diasUteis); return d;
}

async function criar(patch, who) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  if (!patch.itens || !patch.itens.length) throw new Error('precisa ao menos 1 item');
  const id = uid();
  const itens = patch.itens.map((it, idx) => ({
    id: uid('ci_'),
    ordem: idx + 1,
    produto_id: it.produtoId || null,
    produto_nome: it.produtoNome || '',
    sku: it.sku || '',
    qtd: Number(it.qtd) || 0,
    custo_unit_estimado: Number(it.custoUnit || 0),
    valor_estimado: (Number(it.qtd)||0) * (Number(it.custoUnit)||0),
    observacoes: it.observacoes || null,
  }));
  const total = itens.reduce((s, x) => s + x.valor_estimado, 0);
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query(`INSERT INTO bi_compra_solicitacao
      (id, empresa_id, empresa_bi, fornecedor_id, fornecedor_nome, urgencia, justificativa, observacoes,
       valor_estimado_total, status, solicitante_username, historico)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
      [id, patch.empresaId || null, patch.empresaBI || null, patch.fornecedorId || null,
       patch.fornecedorNome || null, patch.urgencia || 'normal',
       patch.justificativa || null, patch.observacoes || null,
       total, STATUS.RASCUNHO, who || null,
       JSON.stringify([{ ts: new Date().toISOString(), tipo: 'criada', who }])]);
    for (const it of itens) {
      await client.query(`INSERT INTO bi_compra_item
        (id, solicitacao_id, ordem, produto_id, produto_nome, sku, qtd, custo_unit_estimado, valor_estimado, observacoes)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
        [it.id, id, it.ordem, it.produto_id, it.produto_nome, it.sku, it.qtd, it.custo_unit_estimado, it.valor_estimado, it.observacoes]);
    }
    await client.query('COMMIT');
    return await get(id);
  } catch(e) {
    await client.query('ROLLBACK');
    throw e;
  } finally { client.release(); }
}

async function editar(id, patch, who) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (![STATUS.RASCUNHO, STATUS.AJUSTE].includes(cur.status)) {
    throw new Error('só dá pra editar em rascunho ou ajuste');
  }
  const set = []; const params = [];
  if (patch.empresaId !== undefined) { params.push(patch.empresaId||null); set.push(`empresa_id = $${params.length}`); }
  if (patch.empresaBI !== undefined) { params.push(patch.empresaBI||null); set.push(`empresa_bi = $${params.length}`); }
  if (patch.fornecedorId !== undefined) { params.push(patch.fornecedorId||null); set.push(`fornecedor_id = $${params.length}`); }
  if (patch.fornecedorNome !== undefined) { params.push(patch.fornecedorNome||null); set.push(`fornecedor_nome = $${params.length}`); }
  if (patch.urgencia !== undefined) { params.push(patch.urgencia); set.push(`urgencia = $${params.length}`); }
  if (patch.justificativa !== undefined) { params.push(patch.justificativa); set.push(`justificativa = $${params.length}`); }
  if (patch.observacoes !== undefined) { params.push(patch.observacoes); set.push(`observacoes = $${params.length}`); }
  if (set.length) {
    set.push(`updated_at = NOW()`);
    params.push(id);
    await pool.query(`UPDATE bi_compra_solicitacao SET ${set.join(', ')} WHERE id = $${params.length}`, params);
  }
  // Itens — se vier patch.itens, sobrescreve
  if (Array.isArray(patch.itens)) {
    await pool.query('DELETE FROM bi_compra_item WHERE solicitacao_id = $1', [id]);
    let total = 0;
    for (let i = 0; i < patch.itens.length; i++) {
      const it = patch.itens[i];
      const qtd = Number(it.qtd) || 0;
      const custo = Number(it.custoUnit) || 0;
      const valor = qtd * custo;
      total += valor;
      await pool.query(`INSERT INTO bi_compra_item
        (id, solicitacao_id, ordem, produto_id, produto_nome, sku, qtd, custo_unit_estimado, valor_estimado, observacoes)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
        [uid('ci_'), id, i+1, it.produtoId||null, it.produtoNome||null, it.sku||null, qtd, custo, valor, it.observacoes||null]);
    }
    await pool.query('UPDATE bi_compra_solicitacao SET valor_estimado_total = $2, updated_at = NOW() WHERE id = $1', [id, total]);
  }
  await _audit(id, 'editado', who, patch);
  // Se estava em ajuste, volta pra aguardando
  if (cur.status === STATUS.AJUSTE) {
    await pool.query(`UPDATE bi_compra_solicitacao SET status=$2, token_aprovacao=$3, token_expira_em=$4 WHERE id=$1`,
      [id, STATUS.AGUARDANDO, _newToken(), _expiraEm()]);
    await _audit(id, 'reenviada-aprovacao', who, null);
  }
  return await get(id);
}

async function submeter(id, who) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (![STATUS.RASCUNHO, STATUS.AJUSTE].includes(cur.status)) throw new Error('status inválido pra submeter: ' + cur.status);
  if (!cur.fornecedor_id && !cur.fornecedor_nome) throw new Error('precisa de fornecedor sugerido');
  if (!cur.itens || cur.itens.length === 0) throw new Error('precisa ao menos 1 item');
  const token = _newToken();
  await pool.query(`UPDATE bi_compra_solicitacao
    SET status=$2, token_aprovacao=$3, token_expira_em=$4, submetida_em=NOW(), updated_at=NOW() WHERE id=$1`,
    [id, STATUS.AGUARDANDO, token, _expiraEm()]);
  await _audit(id, 'submetida', who, { token });
  return await get(id);
}

async function aprovar(id, by, byPhone) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (cur.status !== STATUS.AGUARDANDO) throw new Error('status inválido pra aprovar: ' + cur.status);
  await pool.query(`UPDATE bi_compra_solicitacao
    SET status=$2, aprovador_username=$3, aprovador_telefone=$4, decidida_em=NOW(), updated_at=NOW() WHERE id=$1`,
    [id, STATUS.APROVADA, by || null, byPhone || null]);
  await _audit(id, 'aprovada', by, { phone: byPhone });
  return await get(id);
}

async function reprovar(id, by, motivo, byPhone) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (cur.status !== STATUS.AGUARDANDO) throw new Error('status inválido pra reprovar: ' + cur.status);
  await pool.query(`UPDATE bi_compra_solicitacao
    SET status=$2, aprovador_username=$3, aprovador_telefone=$4, decidida_em=NOW(), motivo=$5, updated_at=NOW() WHERE id=$1`,
    [id, STATUS.REPROVADA, by || null, byPhone || null, motivo || 'sem motivo informado']);
  await _audit(id, 'reprovada', by, { motivo, phone: byPhone });
  return await get(id);
}

async function pedirAjuste(id, by, observacao, byPhone) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (cur.status !== STATUS.AGUARDANDO) throw new Error('status inválido: ' + cur.status);
  await pool.query(`UPDATE bi_compra_solicitacao
    SET status=$2, aprovador_username=$3, aprovador_telefone=$4, decidida_em=NOW(), motivo=$5, updated_at=NOW() WHERE id=$1`,
    [id, STATUS.AJUSTE, by || null, byPhone || null, observacao || '']);
  await _audit(id, 'ajuste-pedido', by, { observacao, phone: byPhone });
  return await get(id);
}

async function marcarPedidoEnviado(id, who, anexoUrl) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  const cur = await get(id);
  if (!cur) throw new Error('solicitação não encontrada');
  if (cur.status !== STATUS.APROVADA) throw new Error('só pode marcar como enviado após aprovação');
  await pool.query(`UPDATE bi_compra_solicitacao
    SET status=$2, pedido_enviado_em=NOW(), pedido_enviado_por=$3, updated_at=NOW() WHERE id=$1`,
    [id, STATUS.PEDIDO_ENVIADO, who || null]);
  await _audit(id, 'pedido-enviado', who, { anexoUrl });
  return await get(id);
}

async function vincularNf(id, nfId, who) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  await pool.query(`UPDATE bi_compra_solicitacao
    SET nf_id=$2, status=$3, recebida_em=NOW(), updated_at=NOW() WHERE id=$1`,
    [id, nfId, STATUS.RECEBIDA]);
  await _audit(id, 'nf-vinculada', who, { nfId });
}

async function cancelar(id, who, motivo) {
  const pool = _pool(); if (!pool) throw new Error('Postgres não conectado');
  await pool.query(`UPDATE bi_compra_solicitacao SET status='cancelada', motivo=$2, updated_at=NOW() WHERE id=$1`,
    [id, motivo || 'cancelada manualmente']);
  await _audit(id, 'cancelada', who, { motivo });
}

async function listAll(opts = {}) {
  const pool = _pool(); if (!pool) return [];
  const conds = []; const params = [];
  if (opts.status) { params.push(opts.status); conds.push(`s.status = $${params.length}`); }
  if (opts.fornecedorId) { params.push(opts.fornecedorId); conds.push(`s.fornecedor_id = $${params.length}`); }
  if (opts.empresaId) { params.push(opts.empresaId); conds.push(`s.empresa_id = $${params.length}`); }
  if (opts.solicitanteUsername) { params.push(opts.solicitanteUsername); conds.push(`s.solicitante_username = $${params.length}`); }
  const where = conds.length ? 'WHERE ' + conds.join(' AND ') : '';
  const r = await pool.query(`
    SELECT s.*, e.nome AS empresa_nome, f.nome AS fornecedor_nome_db,
      (SELECT COUNT(*) FROM bi_compra_item i WHERE i.solicitacao_id = s.id) AS itens_count
    FROM bi_compra_solicitacao s
    LEFT JOIN bi_empresas e ON e.id = s.empresa_id
    LEFT JOIN bi_fornecedores f ON f.id = s.fornecedor_id
    ${where}
    ORDER BY s.created_at DESC
    LIMIT 200
  `, params);
  return r.rows;
}

async function get(id) {
  const pool = _pool(); if (!pool) return null;
  const cab = await pool.query(`
    SELECT s.*, e.nome AS empresa_nome, f.nome AS fornecedor_nome_db, f.doc AS fornecedor_doc,
      f.email AS fornecedor_email, f.telefone AS fornecedor_telefone
    FROM bi_compra_solicitacao s
    LEFT JOIN bi_empresas e ON e.id = s.empresa_id
    LEFT JOIN bi_fornecedores f ON f.id = s.fornecedor_id
    WHERE s.id = $1
  `, [id]);
  if (!cab.rows[0]) return null;
  const itens = await pool.query(`
    SELECT i.*, p.nome AS produto_nome_db, p.sku AS produto_sku_db, p.custo_medio AS custo_atual
    FROM bi_compra_item i
    LEFT JOIN bi_produtos p ON p.id = i.produto_id
    WHERE i.solicitacao_id = $1 ORDER BY i.ordem
  `, [id]);
  return { ...cab.rows[0], itens: itens.rows };
}

async function getByToken(token) {
  const pool = _pool(); if (!pool) return null;
  if (!token) return null;
  const r = await pool.query('SELECT id FROM bi_compra_solicitacao WHERE token_aprovacao = $1', [String(token).toUpperCase()]);
  if (!r.rows[0]) return null;
  return await get(r.rows[0].id);
}

async function _audit(id, tipo, who, payload) {
  const pool = _pool(); if (!pool) return;
  const event = { ts: new Date().toISOString(), tipo, who: who || null, payload: payload || null };
  await pool.query(`UPDATE bi_compra_solicitacao SET historico = historico || $2::jsonb WHERE id = $1`,
    [id, JSON.stringify([event])]);
}

// Tenta achar uma solicitação aprovada/enviada que combine com uma NF recém-chegada
// Critério: fornecedor (por CNPJ via bi_fornecedores) + valor_total_próximo (±10%)
async function sugerirMatchParaNf({ emitenteCnpj, valorTotal }) {
  const pool = _pool(); if (!pool || !emitenteCnpj) return [];
  const minV = valorTotal * 0.9, maxV = valorTotal * 1.1;
  const r = await pool.query(`
    SELECT s.*, f.nome AS fornecedor_nome_db
    FROM bi_compra_solicitacao s
    JOIN bi_fornecedores f ON f.id = s.fornecedor_id
    WHERE regexp_replace(coalesce(f.doc,''), '\\D', '', 'g') = $1
      AND s.status IN ('aprovada','pedido_enviado')
      AND s.valor_estimado_total BETWEEN $2 AND $3
    ORDER BY ABS(s.valor_estimado_total - $4) ASC
    LIMIT 5
  `, [emitenteCnpj, minV, maxV, valorTotal]);
  return r.rows;
}

module.exports = {
  STATUS, URGENCIAS,
  ensureTable,
  criar, editar, submeter,
  aprovar, reprovar, pedirAjuste,
  marcarPedidoEnviado, vincularNf, cancelar,
  listAll, get, getByToken,
  sugerirMatchParaNf,
};
